"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "j", run = "arrow +1" },
  { on = "k", run = "arrow -1" },
  { on = "<C-o>", run = '''shell --block "nvim +'lua require(\"persistence\").load()'" --confirm''' },
  { on = [
    "c",
    "s",
  ], run = '''shell 'curl -F"file=@$1" https://0x0.st | pbcopy' --confirm''', desc = "Share file" },
  { on = "e", run = "plugin run-file 1", desc = "Execute file (sync)" },
  { on = "E", run = "plugin run-file 2", desc = "Execute file with args (sync)" },
  { on = "<C-e>", run = "plugin run-file 3", desc = "Execute file with args (async)" },
  { on = [
    "c",
    "a",
  ], run = "plugin compress", desc = "Archive selected files" },
  { on = [
    "c",
    "m",
  ], run = "plugin chmod", desc = "chmod" },
  { on = "T", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [
    "g",
    "r",
  ], run = '''shell 'ya emit cd "$(git rev-parse --show-toplevel)"' ''', desc = "Go to git root" },
  { on = [
    "C",
    "d",
  ], run = "cd ~/Documents" },
  { on = [
    "C",
    "h",
  ], run = "cd ~" },
  { on = [
    "C",
    "D",
  ], run = "cd ~/Downloads" },
  { on = [
    "C",
    "c",
  ], run = "cd ~/.config" },
  { on = [
    "C",
    "C",
  ], run = "cd ~/.dotfiles" },
  { on = [
    "C",
    "l",
  ], run = "cd ~/.local" },
  { on = [
    "C",
    "P",
  ], run = "cd ~/Documents/personal" },
]
