[mgr]
ratio = [1, 2, 3]
sort_by = "mtime"
sort_reverse = true
sort_translit = true
show_hidden = true
show_symlink = false

[preview]
wrap = "yes"
# to use dynamic values provided by my system instead
max_width = 9999
max_height = 9999

[tasks]
image_alloc = 0
image_bound = [0, 0]

[[opener.open_in_browser]]
run = '$BROWSER "$@"'
desc = "$BROWSER"
orphan = true
for = "unix"

[[open.prepend_rules]]
mime = "application/pdf"
use = ["open_in_browser"]

[[plugin.prepend_fetchers]]
url   = "*"
run   = "git"
group = "git"

[[plugin.prepend_fetchers]]
url   = "*/"
run   = "git"
group = "git"
