---
- name: Close any open System Preferences panes
  ansible.builtin.command:
    cmd: osascript -e 'tell application "System Preferences" to quit'
  changed_when: false

- name: Set macOS default settings
  community.general.osx_defaults:
    domain: "{{ item['domain'] }}"
    key: "{{ item['key'] }}"
    type: "{{ item['type'] | default(omit) }}"
    value: "{{ item['value'] }}"
  loop: "{{ macos_defaults }}"
  loop_control:
    label: "{{ item['name'] }}"
  notify: Restart dock

- name: Set macOS default settings from xml files
  ansible.builtin.command:
    cmd: "defaults import {{ item['key'] }} {{ myansible_dir }}/roles/system_defaults/files/macos/xml_settings/{{ item['filename'] }}"
  loop: "{{ macos_defaults_xml }}"
  loop_control:
    label: "{{ item['key'] }}"
  changed_when: false
  notify: Restart dock

- name: Unhide ~/Library
  ansible.builtin.command: "chflags nohidden {{ ansible_user_dir }}/Library"
  changed_when: false

- name: Remove extended attributes on ~/Library
  ansible.builtin.command: "xattr -c {{ ansible_user_dir }}/Library"
  changed_when: false

- name: Unhide /Volumes
  ansible.builtin.command: chflags nohidden /Volumes
  changed_when: false
  become: true

- name: get current wallpapper
  ansible.builtin.command:
    cmd: 'osascript -e "tell app \"finder\" to get posix path of (get desktop picture as alias)"'
  register: wallpapper
  changed_when: false
  failed_when: false
  tags: ['wallpapper']

# if you want hacky set for all desktops - https://gabrieldougherty.com/posts/macos-change-desktop-background-image/
- name: set wallpapper
  ansible.builtin.command:
    cmd: 'osascript -e "tell application \"System Events\" to tell every desktop to set picture to \"{{ wallpaper_path }}\" as POSIX file"'
  when: wallpapper.stdout != wallpaper_path
  tags: ['wallpapper']
