#!/usr/bin/env bash

USER_APPS="";

ROOT_APPS="
nvim,zsh,x11,
shell,picom,lf,
fontconfig,
dunst,suckless,
bin,lvim,wallpapers,
zathura,pipewire,
runit,skippy,
backup"

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS $(dirname $(realpath $0))/install "$@"
