#!/usr/bin/env bash

USER_APPS="git,packup,personal";

ROOT_APPS="
nvim,zsh,x11,
shell,picom,lf,
fontconfig,
dunst,suckless,
bin,lvim,wallpapers,
zathura,pipewire,
runit,skippy"

INSTALL_PATH=$(dirname $(realpath $0))/install

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS $INSTALL_PATH
