#!/bin/sh

curl -LO https://github.com/Keep-Simple/.dotfiles/archive/refs/heads/macos.tar.gz
tar -xzvf ./macos.tar.gz
rm ./macos.tar.gz
mv .dotfiles-macos ~/.dotfiles
~/.dotfiles/backup/macos-full-setup.sh
