#!/bin/sh

curl -LO https://github.com/Keep-Simple/.dotfiles/archive/refs/heads/macos.tar.gz
tar -xzvf ./macos.tar.gz
rm ./macos.tar.gz
if [ -d ~/.dotfiles ]; then
	sudo rm -rf ~/.dotfiles
fi
mv .dotfiles-macos/ ~/.dotfiles/
~/.dotfiles/backup/macos-full-setup.sh
