#!/usr/bin/env bash

USER_APPS=""

ROOT_APPS="
lf,bin,lvim,
alacritty,
karabiner,skhd,yabai,
shell,zsh,
zathura,k9s,
git,spotify-tui,
asdf,tmux,
btop,bat
"

cd ~/.dotfiles

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS ./backup/install-dotfiles "$@"
