#!/usr/bin/env bash

USER_APPS="";

ROOT_APPS="
nvim,zsh,
shell,lf,
bin,lvim,
alacritty,iterm2,
karabiner,skhd,yabai
"

ROOT_APPS=$ROOT_APPS USER_APPS=$USER_APPS $(dirname $(realpath $0))/install "$@"



