#!/usr/bin/env bash

# run the stow command for the passed in directory ($2) in location $1
unstowit() {
    usr=$1
    app=$2
    # -v verbose
    # -R recursive
    # -t target
    stow -v -D -t ${usr} ${app}
}

echo ""
echo "Unstowing apps for user: ${whoami}"

# install apps available to local users and root
for app in $(echo $ROOT_APPS | sed "s/,/ /g"); do
    unstowit "${HOME}" $app 
done

# install only user space folders
for app in $(echo $USER_APPS | sed "s/,/ /g"); do
    if [[ "$(whoami)" != *"root"* ]]; then
        unstowit "${HOME}" $app 
    fi
done

echo ""
echo "##### ALL DONE"


