---
- name: Include macOS package tasks
  ansible.builtin.import_tasks: os_Darwin.yaml
  when: ansible_facts['system'] == 'Darwin'

- name: Include Linux package tasks
  ansible.builtin.import_tasks: os_Linux.yaml
  when: ansible_facts['system'] == 'Linux'
