---
- name: Symlink project overrides
  ansible.builtin.include_tasks: project_overrides.yaml

- name: Install tmux plugin manager
  ansible.builtin.git:
    repo: https://github.com/tmux-plugins/tpm
    dest: "{{ ansible_facts['user_dir'] }}/.tmux/plugins/tpm"

- name: Register tpm plugins
  stat:
    path: "{{ ansible_facts['user_dir'] }}/.config/tmux/plugins"
  register: tpm_plugins

- name: Install tpm plugins
  ansible.builtin.command:
    cmd: "{{ ansible_facts['user_dir'] }}/.tmux/plugins/tpm/bin/install_plugins"
  when: not tpm_plugins.stat.exists

- name: Install pre-commit hooks in dotfiles repo
  ansible.builtin.command:
    cmd: pre-commit install
    chdir: "{{ dotfiles.target }}"
    creates: "{{ dotfiles.target }}/.git/hooks/pre-commit"
  environment:
    PATH: "{{ homebrew_brew_bin_path | default('') }}:{{ ansible_facts['env'].PATH }}"

- name: Install asdf packages
  ansible.builtin.shell: |
    awk '{print $1}' {{ ansible_facts['user_dir'] }}/.tool-versions | xargs -I _ asdf plugin add _ || true
    asdf install
  args:
    chdir: "{{ ansible_facts['user_dir'] }}"
  register: asdf_result
  changed_when: >
    'The installation was successful!' in asdf_result.stdout
  failed_when: false
