#!/usr/bin/env bash

unstowit() {
	usr=$1
	app=$2
	stow -v -D -t ${usr} ${app}
}

# run the stow command for the passed in directory ($2) in location $1
stowit() {
	usr=$1
	app=$2
	# -v verbose
	# -R recursive
	# -t target
	stow -v -R -t ${usr} ${app}
}

stow_func="stowit"

if [[ $1 == 'd' ]]; then
	stow_func="unstowit"
fi

echo ""
echo "Stowing apps for user: ${whoami}"

# install apps available to local users and root
for app in $(echo $ROOT_APPS | sed "s/,/ /g"); do
	$stow_func "${HOME}" $app
done

# install only user space folders
for app in $(echo $USER_APPS | sed "s/,/ /g"); do
	if [[ "$(whoami)" != *"root"* ]]; then
		$stow_func "${HOME}" $app
	fi
done

echo ""
echo "##### ALL DONE"
