#!/usr/bin/env sh

# apps shortcuts
ctrl + alt + cmd - return : open -n /Applications/Alacritty.app
ctrl + alt + cmd - b : open -n /Applications/Brave\ Browser.app
# change layouts
ctrl + alt + cmd - t : yabai -m space --layout bsp 
ctrl + alt + cmd - u : yabai -m space --layout stack

# i3 like window focus
ctrl + alt + cmd - j : yabai -m window --focus $(yabai -m query --windows --space | jq 'sort_by(.frame.y, .frame.x, .id) | .[(to_entries | .[] | select(.value."has-focus" == true) | .key - 1) % length] | .id')
ctrl + alt + cmd - k : yabai -m window --focus $(yabai -m query --windows --space | jq 'sort_by(.frame.y, .frame.x, .id) | .[(to_entries | .[] | select(.value."has-focus" == true) | .key + 1) % length] | .id')

# i3 like window swapping
ctrl + alt + cmd + shift - j : yabai -m window --swap $(yabai -m query --windows --space | jq 'sort_by(.frame.y, .frame.x, .id) | .[(to_entries | .[] | select(.value."has-focus" == true) | .key - 1) % length] | .id')
ctrl + alt + cmd + shift - k : yabai -m window --swap $(yabai -m query --windows --space | jq 'sort_by(.frame.y, .frame.x, .id) | .[(to_entries | .[] | select(.value."has-focus" == true) | .key + 1) % length] | .id')

# resize window
ctrl + alt + cmd - h : yabai -m window --resize left:-50:0; yabai -m window --resize right:-50:0
ctrl + alt + cmd - l : yabai -m window --resize right:50:0; yabai -m window --resize left:50:0

# fast focus previous and next desktop
ctrl + alt + cmd - g : yabai -m space --focus prev || yabai -m space --focus last
ctrl + alt + cmd - 0x29 : yabai -m space --focus next || yabai -m space --focus first

# toggle sticky (show on all spaces)
ctrl + alt + cmd - s : yabai -m window --toggle sticky --layer above --toggle topmost
# toggle topmost (keep above other windows)
ctrl + alt + cmd - o : yabai -m window --toggle topmost
## Close active application
ctrl + alt + cmd - q : yabai -m window --close
# toggle window zoom
ctrl + alt + cmd - f : yabai -m window --toggle zoom-fullscreen
# toggle window native fullscreen
ctrl + alt + cmd + shift - f : yabai -m window --toggle native-fullscreen
# float / unfloat window 
ctrl + alt + cmd + shift - space : yabai -m window --toggle float; yabai -m window --grid 4:4:1:1:2:2
# Restart Yabai
ctrl + alt + cmd - r : launchctl kickstart -k "gui/${UID}/homebrew.mxcl.yabai"; skhd -r

# fast focus desktop
ctrl + alt + cmd - 1 : yabai -m space --focus 1
ctrl + alt + cmd - 2 : yabai -m space --focus 2
ctrl + alt + cmd - 3 : yabai -m space --focus 3
ctrl + alt + cmd - 4 : yabai -m space --focus 4
ctrl + alt + cmd - 5 : yabai -m space --focus 5
ctrl + alt + cmd - 6 : yabai -m space --focus 6
ctrl + alt + cmd - 7 : yabai -m space --focus 7
ctrl + alt + cmd - 8 : yabai -m space --focus 8
ctrl + alt + cmd - 9 : yabai -m space --focus 9

# send window to desktop and follow focus
ctrl + alt + cmd + shift - 1 : yabai -m window --space  1; yabai -m space --focus 1
ctrl + alt + cmd + shift - 2 : yabai -m window --space  2; yabai -m space --focus 2
ctrl + alt + cmd + shift - 3 : yabai -m window --space  3; yabai -m space --focus 3
ctrl + alt + cmd + shift - 4 : yabai -m window --space  4; yabai -m space --focus 4
ctrl + alt + cmd + shift - 5 : yabai -m window --space  5; yabai -m space --focus 5
ctrl + alt + cmd + shift - 6 : yabai -m window --space  6; yabai -m space --focus 6
ctrl + alt + cmd + shift - 7 : yabai -m window --space  7; yabai -m space --focus 7
ctrl + alt + cmd + shift - 8 : yabai -m window --space  8; yabai -m space --focus 8
ctrl + alt + cmd + shift - 9 : yabai -m window --space  9; yabai -m space --focus 9
