---
- name: Register Brewfile
  stat:
    path: "{{ brewfile_dir }}/Brewfile"
  register: brew_file

- block:
    - name: Check if install is needed
      command: "{{ homebrew_brew_bin_path }}/brew bundle check chdir={{ brewfile_dir }}"
      register: brew_check
      changed_when: false
      failed_when: false

    - name: Install from Brewfile
      command: "{{ homebrew_brew_bin_path }}/brew bundle --no-lock chdir={{ brewfile_dir }} "
      async: 10000
      poll: 0
      register: brew_install
      when: brew_check.rc == 1

    - name: Check on install
      async_status:
        jid: '{{ brew_install.ansible_job_id }}'
      when: brew_check.rc == 1
      register: job_result
      until: job_result.finished
      retries: 1000
      delay: 10
  when: brew_file.stat.exists
