---
- name: Register zinit
  stat:
    path: "{{ ansible_user_dir }}/.local/share/zinit"
  register: zinit

- name: Setup zsh
  ansible.builtin.command:
    cmd: zsh -ilc '@zinit-scheduler burst'
  async: 10000
  poll: 2
  when: not zinit.stat.exists

- name: create shortcuts
  ansible.builtin.command:
    cmd: zsh -lc 'apply-shortcuts'
  args:
    creates: "{{ ansible_user_dir }}/.config/shell/shortcutrc"
