---
- name: Setup zsh
  ansible.builtin.command:
    cmd: zsh -ilc '@zinit-scheduler burst'
  args:
    creates: "{{ ansible_user_dir }}/.local/share/zinit"
  async: 10000
  poll: 5

- name: create shortcuts
  ansible.builtin.command:
    cmd: zsh -lc 'apply-shortcuts'
  args:
    creates: "{{ ansible_user_dir }}/.config/shell/shortcutrc"
