---
plugins:
  # Leverage stern (https://github.com/wercker/stern) to output logs.
  stern:
    shortCut: m
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
    command: stern
    background: false
    args:
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT

  log-jq:
    shortCut: Shift-L
    description: "Full logs"
    scopes:
      - pods
    command: bash
    background: false
    args:
      - -c
      - '"$@" | pretty_logs | less'
      - dummy-arg
      - kubectl
      - logs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  raw-logs-follow:
    shortCut: Ctrl-L
    description: Live full logs
    scopes:
      - pods
    command: bash
    background: false
    args:
      - -c
      - '"$@" | pretty_logs'
      - dummy-arg
      - kubectl
      - logs
      - -f
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
      # View user-supplied values when the helm chart was created
  helm-values:
    shortCut: v
    confirm: false
    description: Values
    scopes:
      - helm
    command: sh
    background: false
    args:
      - -c
      - "helm get values $COL-NAME -n $NAMESPACE --kube-context $CONTEXT | less -K"
  dive:
    shortCut: d
    confirm: false
    description: "Dive image"
    scopes:
      - containers
    command: dive
    background: false
    args:
      - $COL-IMAGE
