---
- name: Create config directories to prevent stow conflicts
  file:
    path: "{{ ansible_user_dir }}/{{ item }}"
    state: directory
  loop:
    - .local/bin
    - .local/share
    - .config
    - .zshrc.d

- block:
    - name: stow common dotfiles
      stow:
        state: '{{ dotfiles_state }}'
        dir: "{{ dotfiles.target }}/ansible/roles/dotfiles/files/common"
        package: '{{ item }}'
      with_items:
        - alacritty
        - asdf
        - bat
        - bin
        - btop
        - git
        - k9s
        - lvim
        - spotify-tui

    - name: stow darwin dotfiles
      stow:
        state: '{{ dotfiles_state }}'
        dir: "{{ dotfiles.target }}/ansible/roles/dotfiles/files/macos"
        package: '{{ item }}'
      with_items:
        - karabiner
        - lf
        - shell
        - bin
        - skhd
        - yabai
        - zsh
      when: ansible_os_family == "Darwin"

    - name: stow archlinux dotfiles
      stow:
        state: '{{ dotfiles_state }}'
        dir: "{{ dotfiles.target }}/ansible/roles/dotfiles/files/linux"
        package: '{{ item }}'
      with_items:
        - bin
      when: ansible_os_family == "Arch Linux"
  environment:
    PATH: "{{ homebrew_brew_bin_path }}:{{ ansible_env.PATH }}" # TODO setup PATH to discover stow for linux too
