---

name: devenv-infra
root: <%= ENV["SRC_ROOT"] %>/../devenv-infra

windows:
  - infra:
      layout: main-vertical
      panes:
        - echo "Start docker containers? [y/n]"; read reply; if [[ $reply == "y" ]]; then ensure_docker_up; docker compose up redpanda-console kafka redis redisinsight; else echo Alright; fi
        - nvim readme.md
