---

name: orca
root: <%= ENV["SRC_ROOT"] %>/..
on_project_exit: killall Docker

windows:
  - orca:
      root: <%= ENV["SRC_ROOT"] %>
      panes:
        - nvim_restore_session_for_curr_dir

  - apisec:
      root: <%= ENV["SRC_ROOT"] %>/../apisec
      panes:
        - nvim_restore_session_for_curr_dir

  - contracts:
      root: <%= ENV["SRC_ROOT"] %>/../orca-contracts
      panes:
        - nvim_restore_session_for_curr_dir

  - infra:
      root: <%= ENV["SRC_ROOT"] %>/../devenv-infra
      layout: main-vertical
      panes:
        - echo "Start docker containers? [y/n]"; read reply; if [[ $reply == "y" ]]; then ensure_docker_up; docker compose up redpanda-console kafka redis redisinsight; else echo Alright; fi
        - nvim readme.md

  - cli:
      root: <%= ENV["SRC_ROOT"] %>/../cli
      panes:
        - lf
