theme = "dracula"
client_id = "03a0b49e35304e2180b96f8251849a6e"
client_port = 8080
playback_format = """
{track} • {artists}
{album}
{metadata}"""
tracks_playback_limit = 50
app_refresh_duration_in_ms = 32
playback_refresh_duration_in_ms = 0
cover_image_refresh_duration_in_ms = 2000
page_size_in_rows = 20
track_table_item_max_len = 32
play_icon = "▶"
pause_icon = "▌▌"
liked_icon = "♥"
border_type = "Plain"
progress_bar_type = "Rectangle"
playback_window_position = "Top"
cover_img_length = 9
cover_img_width = 5
cover_img_scale = 1.0
playback_window_width = 6
enable_media_control = true
enable_streaming = true
enable_cover_image_cache = true
enable_notify = false
default_device = "cli-player"

[notify_format]
summary = "{track} • {artists}"
body = "{album}"

[device]
name = "cli-player"
device_type = "speaker"
volume = 70
bitrate = 320
audio_cache = false
