#!/usr/bin/env zsh

# to load $YABAI env
source $HOME/.profile

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config \
	mouse_follows_focus off \
	focus_follows_mouse autoraise \
	window_origin_display default \
	window_placement second_child \
	window_topmost off \
	window_shadow float \
	window_opacity off \
	window_border off \
	window_border_blur off \
	window_border_width 2 \
	window_animation_duration 0.0 \
	window_border_hidpi on \
	active_window_border_color 0xffc4a7e7 \
	normal_window_border_color 0xff6e6a86 \
	layout bsp \
	window_gap 8 \
	split_type auto \
	split_ratio 0.5 \
	insert_feedback_color 0xffd75f5f \
	auto_balance off \
	mouse_modifier ctrl \
	mouse_action1 move \
	mouse_action2 resize \
	mouse_drop_action swap

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add title='Preferences$' manage=off
yabai -m rule --add title='^General' manage=off
yabai -m rule --add title='Settings$' manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="System Preferences" app="^System Preferences$" title=".*" manage=off
yabai -m rule --add label="App Store" app="^App Store$" manage=off
yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
yabai -m rule --add label="Dictionary" app="^Dictionary$" manage=off
yabai -m rule --add label="mpv" app="^mpv$" manage=off
yabai -m rule --add label="Software Update" title="Software Update" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add app="^Karabiner-EventViewer$" manage=off
# yabai -m rule --add app="^Spotify$" manage=off
yabai -m rule --add title="QuickTerminal" grid=20:20:5:5:10:10 sticky=on layer=above opacity=0.9 border=off manage=off

# If no window on the current space is focused after a window is destroyed or
# minimized, or an application is hidden, focus the window under the cursor.
yabai -m signal --add event=window_destroyed action=$YABAI/focus_space.sh
yabai -m signal --add event=window_minimized action=$YABAI/focus_space.sh
yabai -m signal --add event=application_hidden action=$YABAI/focus_space.sh

# yabai -m signal --add event=display_changed action=$YABAI/restart.sh

# pass YABAI env, because of sh not autoloading .profile
yabai -m signal --add event=window_created action="YABAI=$YABAI $YABAI/smart_gaps.sh"
yabai -m signal --add event=window_destroyed action="YABAI=$YABAI $YABAI/smart_gaps.sh"
yabai -m signal --add event=window_minimized action="YABAI=$YABAI $YABAI/smart_gaps.sh"
yabai -m signal --add event=window_deminimized action="YABAI=$YABAI $YABAI/smart_gaps.sh"
yabai -m signal --add event=space_changed action="YABAI=$YABAI $YABAI/smart_gaps.sh"

$YABAI/smart_gaps.sh
SHELL="/bin/sh" skhd &
echo "yabai configuration loaded.."

# notch handling (macbook pro 16) for custom title bar
# NOTCH_UUID="37D8832A-2D66-02CA-B9F7-8F30A301B230"
# NORMAL_BAR=32
# NOTCH_BAR=0
# yabai -m signal --add event=display_added action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar main:$NORMAL_BAR:0; else yabai -m config external_bar all:$NORMAL_BAR:0; fi"
# yabai -m signal --add event=display_removed action="if [[ \"\$(yabai -m query --displays | jq \".[\$YABAI_DISPLAY_ID].uuid\")\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NORMAL_BAR:0; elif [[ \"\$(yabai -m query --displays | jq '.[].uuid')\" =~ \"$NOTCH_UUID\" ]]; then yabai -m config external_bar all:$NOTCH_BAR:0; fi"
# if [[ "$(yabai -m query --displays | jq '.[].uuid')" =~ "$NOTCH_UUID" ]]; then if [ "$(yabai -m query --displays | jq length)" -gt "1" ]; then yabai -m config external_bar main:$NORMAL_BAR:0; else yabai -m config external_bar all:$NOTCH_BAR:0; fi else yabai -m config external_bar all:$NORMAL_BAR:0; fi
