plugin:
  # Leverage stern (https://github.com/wercker/stern) to output logs.
  stern:
    shortCut: m
    confirm: false
    description: "Logs <Stern>"
    scopes:
      - pods
    command: stern
    background: false
    args:
      - $FILTER
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT

  log-jq:
    shortCut: Shift-L
    description: "Full logs"
    scopes:
      - pods
    command: bash
    background: false
    args:
      - -c
      - '"$@" | pretty_logs | less'
      - dummy-arg
      - kubectl
      - logs
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
  raw-logs-follow:
    shortCut: Ctrl-L
    description: Live full logs
    scopes:
      - pods
    command: bash
    background: false
    args:
      - -c
      - '"$@" | pretty_logs'
      - dummy-arg
      - kubectl
      - logs
      - -f
      - $NAME
      - -n
      - $NAMESPACE
      - --context
      - $CONTEXT
