---
- name: Register lazy nvim
  stat:
    path: "{{ ansible_user_dir }}/.local/share/nvim/lazy"
  register: lazy_nvim

- name: First headless run
  ansible.builtin.command:
    cmd: zsh -l -c 'ulimit -n 10240; nvim --headless +quitall &> /dev/null'
  register: init
  until: init is succeeded
  retries: 1
  when: not lazy_nvim.stat.exists
